[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/review"
  to = "/review/index.html"
  status = 200

[[redirects]]
  from = "/review/*"
  to = "/review/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
