[build]
  command = "npm run build"
  publish = "public"

# Disable Next.js plugin since we're doing static export
[[plugins]]
package = "@netlify/plugin-nextjs"

[plugins.inputs]
disabled = true

[[redirects]]
  from = "/review"
  to = "/review/index.html"
  status = 200

[[redirects]]
  from = "/review/*"
  to = "/review/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
